Don't worry about caching

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -12,47 +12,39 @@ VENDOR_DIR="$BUILD_DIR/vendor"
 INSTALL_DIR="$VENDOR_DIR/imagemagick"
 CACHE_FILE="$CACHE_DIR/imagemagick.tar.gz"
 
+# install imagemagick
+IMAGE_MAGICK_VERSION="${IMAGE_MAGICK_VERSION:-6.9.3-10}"
+IMAGE_MAGICK_FILE="ImageMagick-$IMAGE_MAGICK_VERSION.tar.gz"
+IMAGE_MAGICK_DIR="ImageMagick-$IMAGE_MAGICK_VERSION"
+# SSL cert used on imagemagick not recognized by heroku.
+IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
 
-if [ ! -f $CACHE_FILE ]; then
-  # install imagemagick
-  IMAGE_MAGICK_VERSION="${IMAGE_MAGICK_VERSION:-6.9.3-10}"
-  IMAGE_MAGICK_FILE="ImageMagick-$IMAGE_MAGICK_VERSION.tar.gz"
-  IMAGE_MAGICK_DIR="ImageMagick-$IMAGE_MAGICK_VERSION"
-  # SSL cert used on imagemagick not recognized by heroku.
-  IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
+echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
+wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
 
-  echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
-  wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
-
-  echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
-  if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
-    echo "Error: Unable to download ImageMagick" | indent
-    ls $BUILD_DIR | indent
-    exit 1;
-  fi
-  tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
-
-  echo "-----> Building ImageMagick"
-  cd $IMAGE_MAGICK_DIR
-  export CPPFLAGS="-I$INSTALL_DIR/include"
-  export LDFLAGS="-L$INSTALL_DIR/lib"
-  ./configure --prefix=$INSTALL_DIR
-  make && make install
-  cd ..
-  rm -rf $IMAGE_MAGICK_DIR
-
-  # cache for future deploys
-  echo "-----> Caching ImageMagick installation"
-  cd $VENDOR_DIR
-  REL_INSTALL_DIR="imagemagick"
-  tar czf $REL_INSTALL_DIR.tar.gz $REL_INSTALL_DIR
-  mv $REL_INSTALL_DIR.tar.gz $CACHE_FILE
-
-else
-  # cache exists, extract it
-  echo "-----> Extracting ImageMagick $CACHE_FILE => $VENDOR_DIR"
-  tar xzf $CACHE_FILE -C $VENDOR_DIR
+echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
+if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
+  echo "Error: Unable to download ImageMagick" | indent
+  ls $BUILD_DIR | indent
+  exit 1;
 fi
+tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
+
+echo "-----> Building ImageMagick"
+cd $IMAGE_MAGICK_DIR
+export CPPFLAGS="-I$INSTALL_DIR/include"
+export LDFLAGS="-L$INSTALL_DIR/lib"
+./configure --prefix=$INSTALL_DIR
+make && make install
+cd ..
+rm -rf $IMAGE_MAGICK_DIR
+
+# cache for future deploys
+echo "-----> Caching ImageMagick installation"
+cd $VENDOR_DIR
+REL_INSTALL_DIR="imagemagick"
+tar czf $REL_INSTALL_DIR.tar.gz $REL_INSTALL_DIR
+mv $REL_INSTALL_DIR.tar.gz $CACHE_FILE
 
 echo "-----> Writing policy file"
 mkdir -p $INSTALL_DIR/etc/ImageMagick
